apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: k6-perf-test-gcp
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube
      revision: main
      paths:
      - test/k6/k6-perf-test-gcp.js
  container:
    resources:
      requests:
        cpu: 1
        memory: 256Mb
    workingDir: /data/repo/test/k6
  config:
    vus: {type: integer, default: 20}
    duration: {type: string, default: '1m'}
  steps:
  - name: Run test
    container:
      image: grafana/k6:0.49.0
    steps:
    - run:
        shell: mkdir /data/artifacts && k6 run k6-perf-test-gcp.js --vus {{ config.vus }} --duration {{ config.duration }}
        env:
        - name: K6_WEB_DASHBOARD
          value: "true"
        - name: K6_WEB_DASHBOARD_EXPORT
          value: "/data/artifacts/k6-test-report.html"
      steps:
      - name: Saving artifacts
        workingDir: /data/artifacts
        artifacts:
          paths:
          - '*'
