apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: api-vite-test
spec:
  content:
    git:
      uri: https://github.com/fivenp/testkube-oneline
      revision: main
      paths:
        - services/api
  env:
    - name: CI
      value: "true"
    - name: NODE_ENV
      value: "test"
  container:
    image: node:20-alpine
    workingDir: /workspace
  steps:
    - name: install
      run:
        shell: sh
        script: |
          npm ci
    - name: test
      run:
        shell: sh
        script: |
          npm run test
          # npx vitest run --reporter=junit --outputFile ./reports/junit.xml || true
